### PR TITLE
Added CleverAdsSolution SDK plugin

### PR DESCRIPTION
**Pull request by Jedures**
Please add my plugin to your repo

### CODE REVIEW

**Comment by Shchvova** [comment]
This JSON is generated automatically when plug-in is pushed to the it's repo. I'll make you a repo to perform this action later today. You would have to push binaries to `plugins` directory.

**Comment by Shchvova** [comment]
Or do you want to have it on your GitHub account and push updates manually?

**Comment by Jedures** [comment]
I want to use my own GitHub account. Can I do it?

**Comment by Shchvova** [comment]
As you wish. This way you'll have to push updates manually (probably just changing v1 to v2 etc)

**Comment by Jedures** [comment]
Ok, I will need to do pull request every update? Thx

**Comment by Shchvova** [comment]
Basically only difference is that you have to push changes manually to the repository. If you decide to use automation, let me know. Your plugin is live now.

**Comment by Jedures** [comment]
Okay, thanks.

**Comment by Jedures** [comment]
I have a one problem. Corona Simulator Console tell me that plugin.cas not found. Can you help me with advice?

It's my build.settings plugins section
plugins =
	{
		["plugin.cas"] =
		{
			publisherId = "com.cleveradssolutions"
		},
	},

**Comment by Shchvova** [comment]
because your released binaries are not correctly made. You have to put data in tgz in root, not in mac-sim/plugin_cas.lua.
Are you sure you don't want use automation? ¯\_(ツ)_/¯

**Comment by Jedures** [comment]
Oh, my MAC made build without folder. I didnot see it =( Thanks

**Comment by Jedures** [comment]
Ok, it didn't help =(

**Comment by Shchvova** [comment]
Sorry. System assumes artifacts are immutable and they will not be downloaded again. Delete cache in  `~/Solar2DPlugins/Caches/Solar2Directory/cleveradssolutions` and in `~/Library/Application Support/Corona/Simulator/Plugins`

I honestly don't understand why you insist on making this task manually while it can be easily automated.

**Comment by Jedures** [comment]
It doesn't work for me too. I want to use my GitHub account, because we published all our SDK's on it. CleverAdsSolutions is ads sdk for native platforms, Unity3d, Cordova and we want to have support of Solar2D. I dont understand why my Solar2D cant find plugin. ERROR: here was an issue while downloading simulator plugin placeholders:
                    Unable to find plugin 'plugin.cas' for platform 'mac-sim'

**Comment by Shchvova** [comment]
Because your archives in release are wrong. Please enable GitHub Actions and copy automation from plugin template to package them automatically. I already explained that your archives contain incorrect directory structure. Files should be in the root of the artifact not in the subdirectory.

If you use automation on your repo it will produce correct binaries; just won't publish update to the directory. That's that.

**Comment by Shchvova** [comment]
Copy this file and every time you push to plug-ins you would get proper release. You will have to push changes to directory manually.

https://github.com/solar2d/plugin-template/tree/master/.github/workflows

**Comment by Shchvova** [comment]
Also, I can fork you repo and publish automatically. You would be able to push to your repo instead of our it makes you sleep better. Btw, just updating your release won't work, since caching mechanisms.

**Comment by Jedures** [comment]
Ok, let's do it.

**Comment by Shchvova** [comment]
I just left for a meal. Will do afterwards.

**Comment by Jedures** [comment]
Bon appetit!

**Comment by Jedures** [comment]
I recreated my repo from your template but It still doesn't work =(

**Comment by Shchvova** [comment]
I'll fix this for you tonight. Please have patience

**Comment by Jedures** [comment]
Thanks. Sorry for my frequent messages.

**Comment by Shchvova** [comment]
Hey! All done. All it took is 3 clicks. I also fixed readme formatting. So, now, you have to accept invitation to [repo](https://github.com/solar2d/com.cleveradssolutions-plugin.cas) I forked.
Also, don't forget to push back your changes. You can do it by pulling from the fork and pushing to your repo. Then when you push changes to your repo all you have to do to publish the release is to go to https://github.com/solar2d/com.cleveradssolutions-plugin.cas and click synchronize button.
Also, I recommend disabling actions on your repo [here](https://github.com/cleveradssolutions/com.cleveradssolutions-plugin.cas/settings/actions)

**Comment by Jedures** [comment]
Hello, thanks for your support, but it still not working for me =( I tried to reinstall Solar2D, but I have strill an error: 

WARNING: there was an issue while downloading simulator plugin placeholders:
                    Unable to find plugin 'plugin.cas' for platform 'mac-sim':
                    	Custom URL: skipped because no table supportedPlatforms provided for plugin.cas
                    	Locally: no directory /Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas
                    	Locally: no file '/Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas/mac-sim/data.tgz'
                    	Locally: no file '/Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas/data.tgz'
                    	Solar2D Marketplace Directory: skipped because marketplaceId is not set
                    	Solar2D Directory: plugin plugin.cas was not found at Solar2D Directory
                    	Ignore Missing checker: no plugin directory /Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas
                    Unable to find plugin 'plugin.cas' for platform 'lua':
                    	Custom URL: skipped because no table supportedPlatforms provided for plugin.cas
                    	Locally: no directory /Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas
                    	Locally: no file '/Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas/lua/data.tgz'
                    	Locally: no file '/Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas/data.tgz'
                    	Solar2D Marketplace Directory: skipped because marketplaceId is not set
                    	Solar2D Directory: plugin plugin.cas was not found at Solar2D Directory
                    	Ignore Missing checker: no plugin directory /Users/vladislavgorik/Solar2DPlugins/com.cleveradssolution/plugin.cas

**Comment by Shchvova** [comment]
Delete this directories. Also, what is your build settings?

~/Solar2DPlugins
~/Library/Application Support/Corona/Simulator/Plugins

**Comment by Jedures** [comment]
I deleted it before reinstalling Solar
Снимок экрана 2021-11-27 в 12 21 30
2D

**Comment by Jedures** [comment]
Okay, I tried to install it plugin on another PC on Windows, but on it doesn't work too. Can't find plugin.

**Comment by Shchvova** [comment]
This works for me:
[project.zip](https://github.com/solar2d/plugins.solar2d.com/files/7612070/Archive.zip)

**Comment by Shchvova** [comment]
@Jedures  is the issues resolved?

**Comment by Jedures** [comment]
Hello, I didn't have an access for my PC yesterday. I will check it today.

**Comment by Jedures** [comment]
It works now. Thanks!

**Comment by Shchvova** [comment]
What was the issue? I didn't change anything

**Comment by Jedures** [comment]
I don't know =) I simply try again and it works now...

**Pull request merged**
